### PR TITLE
stop reparsing the flowNodes

### PR DESCRIPTION
**Pull request by krakan**
The previous code to abort traversing the node tree when the same node was encountered again didn't actually work which made the plugin unusable for builds with large and complicated node trees.

### CODE REVIEW

**Comment by lsjostro** [comment]
Nice catch @krakan! I'll let @bernhardcygan and/or @jmcshane review it!

**Comment by lsjostro** [comment]
@jmcshane great! do you mind filing that PR to this repo instead?

**Comment by lsjostro** [comment]
Merging this for now. Thanks @krakan!

**Comment by lsjostro** [comment]
Will cut a new release after @jmcshane get the unit tests in place.

**Comment by krakan** [comment]
Great work guys! Thanks for the prompt action!

**Pull request merged**
