### PR TITLE
Add node status metric

### PR DESCRIPTION
**Pull request by cperrin88**
### Changes proposed

Add a new metric that exposes the up/down status of the build nodes.

### Checklist

- [x] Includes tests covering the new functionality?
- [x] Ready for review
- [x] Follows CONTRIBUTING rules

### Notify

@markyjackson-taulia

### CODE REVIEW

**Comment by cperrin88** [comment]
We used this functionality internally and found it very useful. We wanted to contribute it back.

**Comment by markyjackson-taulia** [comment]
@cperrin88 give me a few days to validate this.
Was until included ?

**Comment by cperrin88** [comment]
Hi @markyjackson-taulia. Take your time. What do you mean with "Was until included"?

**Comment by markyjackson-taulia** [comment]
I meant was a unit test included?

**Review by markyjackson-taulia — APPROVED** [review]

**Pull request merged**
