### PR TITLE
Fix Monotonic Counter and Add New Build Counters

### LINKED ISSUE #539: Monotonic counter decreases when builds expire
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

AmazonLinux2

### Reproduction steps

Create a build and run it a few times with both successes and failures
Configure Jenkins to expire/discard old builds
Observe that metrics that are counters go down (successful and failed builds for example)

### Expected Results

Counter. A counter is a cumulative metric that represents a single monotonically increasing counter whose value can only increase or be reset to zero on restart.

### Actual Results

The counters go down, which causes alerts based on these values to fire.

### Anything else?

Reference to closed (but unresolved) issue: https://github.com/jenkinsci/prometheus-plugin/issues/327

Prometheus plugin version: 2.1.2
Jenkins version: 2.375.4

### PR DESCRIPTION
**Pull request by aidanleuck**
Fixes #539 

### Changes proposed

- Added unstable build count metric
- Added aborted build count metric
- Added total build count metric
- Fixes monotonic build counter by using Jenkins RunListener class to listen for completed jobs
- See relevant discussion in #539 as to why this PR should be accepted over #581 

### Checklist

- [ ] Includes tests covering the new functionality?
- [ ] Ready for review
- [ ] Follows CONTRIBUTING rules

### Notify

@Waschndolos

### CODE REVIEW

**Comment by Waschndolos** [comment]
@aidanleuck. Thank you for the PR. Looks promising from what I see. I guess you've tested it already on a Jenkins instance?

**Comment by aidanleuck** [comment]
Hi @Waschndolos, Yeah, I tested on the Jenkins instance just using mvn hpi:run and counters appeared to work as expected. I would love to write some integration tests that kick off a job and then check the counter values. I was unable to find any documentation from Jenkins on how to write this kind of test, but if you are able to point me towards some relevant code/documentation I can add some extra tests to confirm everything is working. Otherwise, the manual verification that I did will have to do.

**Comment by Waschndolos** [comment]
Hi @aidanleuck. I just installed it in our company's test system. Seems like `success_build_count`, `failed_build_count` is working fine. But I didn't manage to get values for `aborted_build_count`, `total_build_count` and `unstable_build_count`. Do they work on your machine?

**Comment by aidanleuck** [comment]
Yeah they were working when I was testing on my local instance at home. I can install on my company's test system tomorrow to validate as well and get back to you. How did you exercise and test the plugin? Did you start any new jobs on the instance? One of the caveats with this plugin is that it will only publish counter metrics once a job has been run. It wont scrape any existing job runs since it only is listening for job completion.

**Comment by Waschndolos** [comment]
@aidanleuck Yes I've started some jobs, aborted them in the middle of the build and so on. Maybe the onCompleted method of BuildCompletionListener is not fired on abort? - But that would be strange..

**Comment by aidanleuck** [comment]
I can't seem to reproduce on my end. Ran a multibranch pipeline job on our test instance. I aborted a job, failed a job, marked one as unstable and marked one as success. All metrics looks to have the correct values. Did you wait for a scrape to occur? The counter only gets updated when the collect method is called. I left my environment down below so we can compare differences to potentially narrow down the issue.

Here is my environment:
Jenkins Version: 2.426.2
Job Type: Multibranch Pipeline
Install Type: Helm Chart/Kubernetes

image
image

**Comment by Waschndolos** [comment]
@aidanleuck Now it also works here. Don't know what happened. I rebuilt the plugin again, redeployed. Now I see the results. Also working if I delete all the builds, start a new one.. Great job! Thank you for contributing! I'm going to merge it later the day. 

One thing.. I don't want to start edit war but are you ok with me changing the "_Member" to "member" then? I have a personal hate relationship with the _ variables - nothing personal :)

**Comment by aidanleuck** [comment]
@Waschndolos Awesome! Glad it is working. Yeah feel free to change the variable names.

**Comment by yogeek** [comment]
@Waschndolos we are currently testing this fix and surprinsingly, we now have an issue on the "namespace" (or "prefix") of some metrics that are still using the default namespace/prefix instead of using the one we configured in the options... 
could it be related ?

image


For example, we configured jenkins to change the default namespace to "gtp" instead of "default" and some metrics are still named "default_xxx" whereas other have the right prefix.

Additionnal details : 
- jenkins version : 2.426.2
- prometheus plugin version : 2.5.0
- we are using Configuration-as-Code plugin to configure all our plugins, including the prometheus-metrics one.

**Comment by Waschndolos** [comment]
Looks strange. Created a Ticket from it: https://github.com/jenkinsci/prometheus-plugin/issues/615

**Pull request merged**
