### PR TITLE
Fix for monotonic counter decreases when builds expire

### LINKED ISSUE #539: Monotonic counter decreases when builds expire
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

AmazonLinux2

### Reproduction steps

Create a build and run it a few times with both successes and failures
Configure Jenkins to expire/discard old builds
Observe that metrics that are counters go down (successful and failed builds for example)

### Expected Results

Counter. A counter is a cumulative metric that represents a single monotonically increasing counter whose value can only increase or be reset to zero on restart.

### Actual Results

The counters go down, which causes alerts based on these values to fire.

### Anything else?

Reference to closed (but unresolved) issue: https://github.com/jenkinsci/prometheus-plugin/issues/327

Prometheus plugin version: 2.1.2
Jenkins version: 2.375.4

### PR DESCRIPTION
**Pull request by adriengardou**
Fixes #539

### Changes proposed

- keep counters values in memory to include discarded runs
- add counters cleaning stage to avoid keeping removed jobs counters
- add node allocation time metric (summary)

### Checklist

- [ ] Includes tests covering the new functionality?
- [ ] Ready for review
- [ ] Follows CONTRIBUTING rules

### Notify

@Waschndolos

### CODE REVIEW

**Comment by adriengardou** [comment]
still in draft to start implementation discussions, but do not yet follow contribution rules.

**Comment by Waschndolos** [comment]
Could you rebase this on the current code base? Tests can be written later, but just so that I fully understand what you changed (Sorry short in time right now)

**Comment by adriengardou** [comment]
I'll do that when have some time. There was quite some modifications since 2.2.2 (which current PR based onto).

**Comment by Waschndolos** [comment]
Closing as https://github.com/jenkinsci/prometheus-plugin/pull/606 was done

**Pull request closed without merging**
