### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by Waschndolos**
The intention behind this refactoring:

Before it was not possible/hard to test the code which fills the metrics. Now all the Collectors are individual, testable classes within package `org/jenkinsci/plugins/prometheus/collectors`.

Having it that way it's possible to avoid calculation of a specific metric if it's not wanted by the user in a more clean way I guess. I've checked the output of the /prometheus endpoint. So far it looked the same. I'll do futher testing before releasing the next version.

### CODE REVIEW

**Comment by Waschndolos** [comment]
(not yet ready - On Vacation for 2 weeks - wanted to test Github CI)

**Comment by Waschndolos** [comment]
change: private final BuildMetrics lastBuildMetrics = new BuildMetrics("_last"); to private final BuildMetrics lastBuildMetrics = new BuildMetrics("last");

**Comment by Waschndolos** [comment]
@markyjackson-taulia Hey there. I've tested this refactoring in our test jenkins instance at work and I compared the output of the endpoint. Looks quite the same as before. Do you think it's ok when I merge this to master? Are there any obstacles regarding git history or so?

**Comment by markyjackson-taulia** [comment]
@Waschndolos git history shouldn't be a problem, but I would do some commit squashing (more a personal preference). 
The only other thing I can think of is if the refactoring changes have any implications on backward compatibility.

**Comment by Waschndolos** [comment]
@markyjackson-taulia wouldn't expect that if it has any impact. The output is the same as far as I see. If there is any I'll tackle it :) Ok I'll check which commits I can squash to make it better and then merge it

**Pull request closed without merging**
