### PR TITLE
change log level to debug

### PR DESCRIPTION
**Pull request by yimgzz**
Fixes https://github.com/jenkinsci/prometheus-plugin/pull/167#issuecomment-712780595

### Changes proposed

https://github.com/jenkinsci/prometheus-plugin/pull/167#issuecomment-712780595

### Checklist

- [ no need ] Includes tests covering the new functionality?
- [+] Ready for review
- [+] Follows CONTRIBUTING rules

### Notify

@markyjackson-taulia

### CODE REVIEW

**Comment by markyjackson-taulia** [comment]
Ci is not passing. Please review

**Comment by h1dden-da3m0n** [comment]
> Ci is not passing. Please review

Since I noticed the Log spam today of this plugin, and see this PR being blocked by a faild CI, may I point at the CI msg:
`/home/jenkins/workspace/Plugins: No space left on device` this has nothing to do with the change of this PR, just that the CI ran out of space while it tried to build this change.

**Review by h1dden-da3m0n — APPROVED** [review]

**Comment by h1dden-da3m0n** [comment]
@markyjackson-taulia sorry to ping you but could you please have another look at this one, it really just touches two lines and the CI failed due to a completely unrelated error (the agent the job was scheduled on had a full HDD/SDD)

NOTE: IMHO change the Jenkinsfile of this plugin to run in a container and it should prevent any future `No space left on device` errors.
```text
buildPlugin(useAci: true)
```

**Comment by h1dden-da3m0n** [comment]
okay that was fast, thank you very much @markyjackson-taulia  :+1: :tada:

**Pull request merged**
