### PR TITLE
remove resource-intensive job checking with ArrayList

### LINKED ISSUE #160: Memory leak
### Steps to reproduce
How can we reproduce the issue
1. upgrade to 2.0.7
2. run for a while
3. Jenkins OOMs

### Expected behaviour
Should work as on 2.0.0 and Prometheus able to scrape for metrics

### Actual behaviour
Jenkins eventually runs out of memory and CPU higher than usual. Nothing specific in logs.

```
INFO: Ping failed. Terminating the channel JNLP4-connect connection from node1/:56060.
java.util.concurrent.TimeoutException: Ping started at 1591711306061 hasn't completed by 1591711551193
	at hudson.remoting.PingThread.ping(PingThread.java:133)
	at hudson.remoting.PingThread.run(PingThread.java:89)

Jun 09, 2020 2:03:55 PM hudson.triggers.Trigger checkTriggers
WARNING: Trigger hudson.triggers.TimerTrigger.run() triggered by org.jenkinsci.plugins.workflow.job.WorkflowJob@58361310[org/repo/master] spent too much time (39 sec) in its execution, other timers can be affected
Jun 09, 2020 2:15:54 PM hudson.remoting.PingThread lambda$new$0
SEVERE: Uncaught exception in PingThread Thread[Ping thread for channel hudson.remoting.Channel@138905d0:JNLP4-connect connection from node1/IP:60232,5,main]
java.lang.OutOfMemoryError: Java heap space

Jun 09, 2020 2:15:41 PM hudson.init.impl.InstallUncaughtExceptionHandler$DefaultUncaughtExceptionHandler uncaughtException
SEVERE: A thread (Periodic background build discarder thread/4083) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.
java.lang.OutOfMemoryError: Java heap spac
```
### Server configuration

**Operating system**:
CentOS 7.8

**Jenkins Version**:
2.222.4

**Plugin Version**:
2.0.7

### Notify

@markyjackson-taulia

### PR DESCRIPTION
**Pull request by yimgzz**
...added check with HashSet

Fixes #160 

### Changes proposed

- Checking whether the job has been processed occurs in a loop with multiple calls of getFullName() and getName(), which causes a heavy load on the CPU if there are many jobs. So I removed this loop and ArrayList and validate the jobs using a HashSet of job names.
Thanks to @a-vorobyev for helping understand this issue.

Before changes:
image
Every 120 seconds 100% CPU used

Thread with anormal CPU time usage:
```
prometheus_async_worker thread
hudson.model.AbstractItem.getFullName(AbstractItem.java:477)
org.jenkinsci.plugins.prometheus.JobCollector.lambda$collect$0(JobCollector.java:168)
org.jenkinsci.plugins.prometheus.JobCollector$$Lambda$313/0x0000000800bcdc40.accept(Unknown Source)
org.jenkinsci.plugins.prometheus.util.Jobs.forEachJob(Jobs.java:20)
org.jenkinsci.plugins.prometheus.JobCollector.collect(JobCollector.java:159)
io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:190)
io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:223)
io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:144)
io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:22)
org.jenkinsci.plugins.prometheus.service.DefaultPrometheusMetrics.collectMetrics(DefaultPrometheusMetrics.java:45)
org.jenkinsci.plugins.prometheus.service.PrometheusAsyncWorker.execute(PrometheusAsyncWorker.java:41)
hudson.model.AsyncPeriodicWork.lambda$doRun$0(AsyncPeriodicWork.java:100)
hudson.model.AsyncPeriodicWork$$Lambda$449/0x0000000800e1e840.run(Unknown Source)
java.base@11.0.6/java.lang.Thread.run(Thread.java:834)
```

After changes:
image
Period is still 120 seconds.

### Checklist

- [+] Includes tests covering the new functionality?
- [+] Ready for review
- [+] Follows CONTRIBUTING rules

### Notify

@markyjackson-taulia

### CODE REVIEW

**Review by markyjackson-taulia — APPROVED** [review]

**Comment by markyjackson-taulia** [comment]
Kindly fix the conflict and I will merge and cut a relase

**Comment by markyjackson-taulia** [comment]
@yimgzz Can not merge until the conflict is addressed. I will leave open for 1 week and close if no action is taken

**Comment by markyjackson-taulia** [comment]
Closing this PR as there has been no response.

**Comment by yimgzz** [comment]
@markyjackson-taulia  Sorry, but i don't saw notifications about your messages. 
I see you changed logic in JobCollector.appendJobMetrics() method, but you forgot to change logging level from info to debug.
By default Jenkins starts with info level, so if we have many(1000+) jobs the name of each job will be logged every 120 second by default. This resource-intensive operation and eat much of disk space.

**Pull request closed without merging**
