### PR TITLE
added a bunch of logging to job collector

### PR DESCRIPTION
**Pull request by johnscancella**

### CODE REVIEW

**Comment by lsjostro** [comment]
cool! Thanks! Would be awesome if you could try it out and debug. I currently don't have time myself. It's pretty easy to start a dev server directly. just run `mvn hpi:run` in the repo and you have a jenkins up'n' running with the plugin. You can then try to recreate the issue with a bunch of bogus jobs.

**Comment by johnscancella** [comment]
If I wanted to test it on the actual server, do I just jar everything up and drop it somewhere and reboot jenkins?

**Comment by johnscancella** [comment]
I tried installing it on the actual server and I can't seem to reproduce the same results. Which JDK did you build with?

**Comment by lsjostro** [comment]
ah cool! I'm using the latest oracle jdk (8).

**Comment by lsjostro** [comment]
going to merge this! Thanks!

**Pull request merged**
