### PR TITLE
chore: bump simple disk usage to include new metric

### PR DESCRIPTION
**Pull request by meiswjn**
Add new disk metric for file count to prometheus metrics plugin (introduced in #https://github.com/jenkinsci/cloudbees-disk-usage-simple-plugin/pull/92)

### Changes proposed

- Bump cloudbees-disk-usage-simple-plugin to 187.v6378d330d1d4 (adds new file count metric)
 
### Checklist

- [ ] Includes tests covering the new functionality?
- [ ] Ready for review
- [ ] Follows CONTRIBUTING rules

### Notify

@Waschndolos

### CODE REVIEW

**Comment by Waschndolos** [comment]
Sounds like a good improvement. Thank you, looking forward for the PR 👍

**Comment by Waschndolos** [comment]
@meiswjn. Did you already start with the implementation? Otherwise I would implement that feature today and close this PR?

**Comment by meiswjn** [comment]
Hey @Waschndolos, not yet - that would be wonderful! Thanks!

**Comment by Waschndolos** [comment]
Ok perfect. I've tracked it here: https://github.com/jenkinsci/prometheus-plugin/issues/590. Closing this PR then

**Pull request closed without merging**
