### PR TITLE
Allow slashes in path and add authentication for the metrics endpoint

### PR DESCRIPTION
**Pull request by coder-hugo**
The PR will add the following new features to the plugin:
1. add possibility to configure the plugin within the global settings of the Jenkins not via an environment variable
2. allow slashes in the prometheus endpoint path
3. add possibility to enable authentication for the prometheus endpoint

### CODE REVIEW

**Comment by lsjostro** [comment]
Awesome! will review it this weekend!
Cheers!

**Comment by lsjostro** [comment]
LGTM! going to merge this! Thank you once again!

**Comment by coder-hugo** [comment]
Thanks for merging this. Will there be a new release of the plugin containing this change in the near future?

**Comment by lsjostro** [comment]
yes, will prepare a new release soonish!

**Pull request merged**
