### PR TITLE
Applying to adopt this plugin

### PR DESCRIPTION
**Pull request by markyjackson-taulia**
I would like to adopt this plugin. I have placed a post in the Jenkins-dev google group.

### CODE REVIEW

**Comment by markyjackson-taulia** [comment]
Jenkins Infra name: jequals5

**Comment by markyjackson-taulia** [comment]
@lsjostro can you confirm here that we are transferring the plugin to me based on our conversation here: https://github.com/jenkinsci/prometheus-plugin/issues/60#issuecomment-418618759

**Comment by lsjostro** [comment]
@markyjackson-taulia approve!

**Comment by oleg-nenashev** [comment]
Thanks @lsjostro! I will proceed with the transfer request here: https://groups.google.com/forum/#!msg/jenkinsci-dev/VVjUBFmoJqg/NKoCzMDCBAAJ

**Pull request merged**
