### PR TITLE
Aggregating stats on multibranch projects

### LINKED ISSUE #500: Option to aggregate PR-builds from same place
### What feature do you want to see added?

With projects that are large, with many PRs, metrics are potentially too large, giving too much detail between different PRs, where differences between PRs is not helpful for metrics given the extra storage and bandwidth required.

As an SRE managing metrics and dashboards for Jenkins builds,
I would like to simplify and simplify the aggregation across PRs of the same build,
so that I don't have to store and transmit so much data and Prometheus doesn't have to work so hard to aggregate it at query time.

For example, if I have a build with 2 PRs, and it shows statistics like this:
```
     default_jenkins_builds_duration_milliseconds_summary_count{jenkins_job="mybuild/PR-481"} 1.0
     default_jenkins_builds_duration_milliseconds_summary_sum{jenkins_job="mybuild/PR-481"} 2000.0
     default_jenkins_builds_duration_milliseconds_summary_count{jenkins_job="mybuild/PR-81"} 3.0
     default_jenkins_builds_duration_milliseconds_summary_sum{jenkins_job="mybuild/PR-81"} 4000.0
```

with this option enabled, it would aggregate like so:
```
     default_jenkins_builds_duration_milliseconds_summary_count{jenkins_job="mybuild"} 4.0
     default_jenkins_builds_duration_milliseconds_summary_sum{jenkins_job="mybuild"} 6000.0
```

(and for all other per-build metrics)

We will want to continue to differentiate on the other labels. "buildable" and "repo"

### Upstream changes

_No response_

### PR DESCRIPTION
**Pull request by seguins**
Fixes #500 

### Changes proposed

- Add an option to aggregate stats on multibranch projects

### Checklist

- [ ] Includes tests covering the new functionality?
- [x] Ready for review
- [x] Follows CONTRIBUTING rules

### Notify

@Waschndolos I tried something to aggregate stats only for multibranch builds, what do you think ?
I would like to add an option to disable the observation of stages. Can I add it to this PR ?

### CODE REVIEW

**Comment by Waschndolos** [comment]
Hi, thanks for the PR. I'm not sure if that will fix the problem. Let's say you have a multibranch job with `branch_A` with 10 builds, `branch_B` with 1 build, `branch_C` with 200 builds. Now you have a metric like available_builds_count. What would be the result here? I would guess it's kind of random depending which `Job` object is passed to the method - unsure, maybe I'm overseeing something here.

**Comment by seguins** [comment]
I asked me the same question, so I tried and looked into the code : 
1. On each collector's execution, [we recreate the counter](https://github.com/jenkinsci/prometheus-plugin/blob/0075069bfa2be61cb19b838d8f24560aea472f80/src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java#L204), so they are reset
2. For each job, [we calculate the metric](https://github.com/jenkinsci/prometheus-plugin/blob/0075069bfa2be61cb19b838d8f24560aea472f80/src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java#L294), and [set it into the counter](https://github.com/jenkinsci/prometheus-plugin/blob/0075069bfa2be61cb19b838d8f24560aea472f80/src/main/java/org/jenkinsci/plugins/prometheus/metrics/jobs/NbBuildsGauge.java#L27)
3. In the prometheus library, the [set method](https://github.com/prometheus/client_java/blob/db2304d042a8f9373504b167efcfbbea13a9e1cd/simpleclient/src/main/java/io/prometheus/client/Gauge.java#L170) create [the addition itself](https://github.com/prometheus/client_java/blob/db2304d042a8f9373504b167efcfbbea13a9e1cd/simpleclient/src/main/java/io/prometheus/client/DoubleAdder.java#L67). In this case I give you link to the Gauge type, but it the same the other types.

**Comment by Waschndolos** [comment]
Hey. I just merged my refactoring into the master branch. Maybe you can update your branch as well. What just came into my mind. Now all the individual collectors are located in ```org/jenkinsci/plugins/prometheus/collectors```. Maybe we could create like a composite class that will be injected in case the stats should be grouped. That class could then perform the aggregation in the form which is correct. Like for build runtime e.g. summarize all runtimes of all branches? for build status return the most failing? I don't know

**Comment by seguins** [comment]
I'm not sure to understand what you mean.
I tried something (that currently doesn't work). Is it the kind of changes you were thinking ? 

I will be away for the end of the week. Feel free to discard my PR and open a new PR on your side 😉

**Pull request closed without merging**
