### PR TITLE
Add metrics for individual runs, fix stage detection

### LINKED ISSUE #160: Memory leak
### Steps to reproduce
How can we reproduce the issue
1. upgrade to 2.0.7
2. run for a while
3. Jenkins OOMs

### Expected behaviour
Should work as on 2.0.0 and Prometheus able to scrape for metrics

### Actual behaviour
Jenkins eventually runs out of memory and CPU higher than usual. Nothing specific in logs.

```
INFO: Ping failed. Terminating the channel JNLP4-connect connection from node1/:56060.
java.util.concurrent.TimeoutException: Ping started at 1591711306061 hasn't completed by 1591711551193
	at hudson.remoting.PingThread.ping(PingThread.java:133)
	at hudson.remoting.PingThread.run(PingThread.java:89)

Jun 09, 2020 2:03:55 PM hudson.triggers.Trigger checkTriggers
WARNING: Trigger hudson.triggers.TimerTrigger.run() triggered by org.jenkinsci.plugins.workflow.job.WorkflowJob@58361310[org/repo/master] spent too much time (39 sec) in its execution, other timers can be affected
Jun 09, 2020 2:15:54 PM hudson.remoting.PingThread lambda$new$0
SEVERE: Uncaught exception in PingThread Thread[Ping thread for channel hudson.remoting.Channel@138905d0:JNLP4-connect connection from node1/IP:60232,5,main]
java.lang.OutOfMemoryError: Java heap space

Jun 09, 2020 2:15:41 PM hudson.init.impl.InstallUncaughtExceptionHandler$DefaultUncaughtExceptionHandler uncaughtException
SEVERE: A thread (Periodic background build discarder thread/4083) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.
java.lang.OutOfMemoryError: Java heap spac
```
### Server configuration

**Operating system**:
CentOS 7.8

**Jenkins Version**:
2.222.4

**Plugin Version**:
2.0.7

### Notify

@markyjackson-taulia

### LINKED ISSUE #161: [JENKINS-62815] Traversal doesn't work on parallel pipelines
### Steps to reproduce
Have a pipeline with at least one parallel section. Try to gather stage duration data. 

### Expected behavior
Stage duration data should be recorded

### Actual behavior
No stage duration data is recorded. (`traverseTree(flownodes)` returns `[]`)

### Server configuration

**Operating system**:

**Jenkins Version**:

**Plugin Version**:
2.0.7

### Suggested fix:
In this file. Switch from a `return False` to a `continue`. The same node can be run into twice if a parallel pipeline is uses. If it is encountered, it should be skipped instead of exiting early, but I have not tested this.
https://github.com/jenkinsci/prometheus-plugin/blob/9a473b0b14ebe5167ef58d8316eb3a2712d5289e/src/main/java/org/jenkinsci/plugins/prometheus/util/FlowNodes.java#L102-L107
```java
            for (final FlowNode next : parents) {
                if (visited.contains(getNodeId(next))) {
                    continue;
                }
                queue.add(next);
            }
```

### Notify

@markyjackson-taulia

~P.S. I'm unable to open a jira at the moment because of the issues with accounts on jenkins.io~
Jira issue is [JENKINS-62815](https://issues.jenkins-ci.org/browse/JENKINS-62815)

### LINKED ISSUE #164: Jobs utils returns repeated items
The current `Jobs.forEachJob` returns repeated items. Please find a possible workaround below, in case you want me to contribute with a fix:

```java
public class Jobs {
    public static void forEachJob(Consumer<Job> consumer) {
        List<Job> jobs = Jenkins.get().getAllItems(Job.class);
        if (jobs != null) {
            for (Job job : jobs) {
                if (job != null) {
                    consumer.accept(job);
                }
            }
        }
    }
}
```

### Steps to reproduce

How can we reproduce the issue

1. Add some nested folders. Example: `job/a/job/b/job/pipeline`
2. Take a look at the `Jobs.forEachJob` output by adding some tracing

### Actual behaviour

Let's suppose we added tracing:

```java
Jobs.forEachJob(j -> System.out.println(j.toString())
```

then:

```
org.jenkinsci...@3c811764[a]
org.jenkinsci...@3c811764[a/b]
org.jenkinsci...@3c811764[a/b/pipeline]
org.jenkinsci...@3c811764[a/b]
org.jenkinsci...@3c811764[a/b/pipeline]
org.jenkinsci...@3c811764[a/b/pipeline]
```

### Expected behaviour

Return a unique list of `Jobs`:

```
org.jenkinsci...@3c811764[a/b/pipeline]
```

### Server configuration

**Operating system**: Debian 10

**Jenkins Version**: Jenkins 2.235.3

**Plugin Version**: Latest version

### Notify

@markyjackson-taulia

### LINKED ISSUE #169: Stage Metrics Missing
Are there any additional plugins or setup configuration to have the staging metrics emitted?

### Steps to reproduce

1. Create a pipeline based job like: 
```
node {
    stage('my test stage') {
        echo "hello"
    }
    stage('another stage') {
        sh("sleep 2")
    }
}
```

### Expected behaviour

There should be prometheus metrics emitted for stage duration for a job - https://github.com/jenkinsci/prometheus-plugin/blob/eb1adb6cee1cc2299ed8a87f728c2db9e4aeae54/src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java#L153

### Actual behaviour

The stage metrics are not present at the metrics endpoint. 

### Server configuration

**Operating system**:
Docker (jenkins/jenkins) - Linux 4.19 amd64
**Jenkins Version**:
2.257
**Plugin Version**:
2.0.7

### Notify

@markyjackson-taulia

### LINKED ISSUE #176: Build Parameters as Label
### Expected behaviour
Additionally to #150 it would be nice to have the parameters for each run as label. For example in our Jenkins the duration of a run depends heavily on the parameters it has been started with (platforms, testsets, etc.). So to get meaningful data (e.g. avg duration) we need a possibility to group by the build parameters.

### Actual behaviour
There are no metrics for individual runs or parameters

### Notify

@markyjackson-taulia

### PR DESCRIPTION
**Pull request by sll552**
Fixes #176 
Fixes #169 
Fixes #164 
Fixes #161 
Fixes #160 
Partially #150 (adds per run metrics but not for individual stages)

### Changes proposed

- Use the same logic to detect the stages as Jenkins does for the pipeline stage view in the UI
- Change the way how jobs are discovered to avoid duplicates and remove the duplicate detection
- Add per run metrics including the parameters and status of each run as label
- Only consider finished stages/runs for duration metrics

### Checklist

- [ ] Includes tests covering the new functionality?
- [x] Ready for review
- [x] Follows CONTRIBUTING rules

### Notify

@markyjackson-taulia

### CODE REVIEW

**Review by markyjackson-taulia — APPROVED** [review]

**Comment by sll552** [comment]
Just saw that I forgot to fix a test, working on it 😓

**Comment by sll552** [comment]
I have removed the test as the code tested was replaced, I hope thats ok

**Comment by markyjackson-taulia** [comment]
Can you just squash your commits

**Comment by sll552** [comment]
Fixed and done

**Review by markyjackson-taulia — APPROVED** [review]

**Comment by markyjackson-taulia** [comment]
I will cut the release tomorrow and thank you 😊

**Comment by sll552** [comment]
No problem, thanks for the fast review/merge 👍

**Comment by ilsl** [comment]
Hi I just tried this but unfortunately, The update broke our prometheus 
Screenshot 2020-10-21 at 15 04 26

Previous Working Plugin Version:
2.0.7

Broken Plugin Version:
2.0.8

**Pull request merged**
