### PR TITLE
[INFRA-2243] - Switch Jenkinsfile to the new buildPluginWithGradle() step

### PR DESCRIPTION
**Pull request by oleg-nenashev**
A part of the Jenkins Pipeline Library update. See  https://issues.jenkins-ci.org/browse/INFRA-2243

### Changes proposed

- Just a Pipeline update

### Checklist

- [x] Includes tests covering the new functionality?
- [x] Ready for review
- [x] Follows CONTRIBUTING rules

### Notify

@markyjackson-taulia

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Huh

```

[2019-09-02T19:44:25.496Z] + ./gradlew --no-daemon cleanTest build

[2019-09-02T19:44:25.496Z] Downloading https://services.gradle.org/distributions/gradle-5.2.1-bin.zip

[2019-09-02T19:44:28.386Z] ...................................................................................

[2019-09-02T19:44:29.763Z] 

[2019-09-02T19:44:29.763Z] Welcome to Gradle 5.2.1!

[2019-09-02T19:44:29.763Z] 

[2019-09-02T19:44:29.763Z] Here are the highlights of this release:

[2019-09-02T19:44:29.763Z]  - Define sets of dependencies that work together with Java Platform plugin

[2019-09-02T19:44:29.763Z]  - New C++ plugins with dependency management built-in

[2019-09-02T19:44:29.763Z]  - New C++ project types for gradle init

[2019-09-02T19:44:29.763Z]  - Service injection into plugins and project extensions

[2019-09-02T19:44:29.763Z] 

[2019-09-02T19:44:29.763Z] For more details see https://docs.gradle.org/5.2.1/release-notes.html

[2019-09-02T19:44:29.763Z] 

[2019-09-02T19:44:29.764Z] To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/5.2.1/userguide/gradle_daemon.html.

[2019-09-02T19:44:30.697Z] Daemon will be stopped at the end of the build stopping after processing

[2019-09-02T19:44:32.603Z] 

[2019-09-02T19:44:32.603Z] FAILURE: Build failed with an exception.

[2019-09-02T19:44:32.603Z] 

[2019-09-02T19:44:32.603Z] * What went wrong:

[2019-09-02T19:44:32.603Z] Task 'cleanTest' not found in root project 'ins_prometheus-plugin_INFRA-2243'.

[2019-09-02T19:44:32.603Z] 

[2019-09-02T19:44:32.603Z] * Try:

[2019-09-02T19:44:32.603Z] Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

```

**Comment by oleg-nenashev** [comment]
@markyjackson-taulia it looks like I got confused by the repo, You actually use Maven instead of Gradle. Would it make sense to remove the Gradle files, Or do you use them somehow?

**Comment by markyjackson-taulia** [comment]
@oleg-nenashev I use it but not solely and it I can remove it this week

**Comment by oleg-nenashev** [comment]
Up to you. I will just close this PR, because it is not something we want

**Pull request closed without merging**
