### PR TITLE
ISSUE-204 - last build metrics don't have stages breakdown

### LINKED ISSUE #204: last build metrics don't have stages breakdown
### Expected behaviour
Should also have:
```
default_jenkins_builds_last_stage_duration_milliseconds_summary_count
default_jenkins_builds_last_stage_duration_milliseconds_summary_sum
```
Though the `count` one is practically meaningless.
In addition, the `default_jenkins_builds_last_build_start_time_milliseconds` metric is not in sync with `default_jenkins_builds_last_build_tests_failing` for example when the latest job is "in flight" and returns the start time of the *next* run

### Actual behaviour
The lastest build metrics we have are:
```
default_jenkins_builds_last_build_tests_total
default_jenkins_builds_last_build_tests_skipped
default_jenkins_builds_last_build_tests_failing
default_jenkins_builds_last_build_start_time_milliseconds
default_jenkins_builds_last_build_result_ordinal
default_jenkins_builds_last_build_result
default_jenkins_builds_last_build_duration_milliseconds
```

### Notify

@markyjackson-taulia

### PR DESCRIPTION
**Pull request by ShimiTaNaka**
Fixes #204 

### Changes proposed

- Add processing of the last completed job, which, we also break down to stages.
- Took the opportunity to unify code between processing a generic run when iterating everything, and when processing the last completed one.
- Added a subclass to handle Run specific metric collectors to make it easier to add more metrics in the future and reduce code duplication

### Checklist

- [ ] Includes tests covering the new functionality?
- [V] Ready for review
- [V] Follows CONTRIBUTING rules

### Notify

@markyjackson-taulia

### CODE REVIEW

**Review by markyjackson-taulia — COMMENTED** [review]
Build failed

**Comment by ShimiTaNaka** [comment]
Also added a testing section to the readme :)
Comments are obviously most welcome

**Comment by markyjackson-taulia** [comment]
@ShimiTaNaka I will have a release out tomorrow

**Comment by ShimiTaNaka** [comment]
Thank you very much for the quick handling

**Comment by clemcvlcs** [comment]
Hi, @markyjackson-taulia , maybe I'm missing something, but I don't see any release integrating these changes. We'd really like to deploy this on our environment. 
Thanks in advance

**Pull request merged**
