### PR TITLE
Change name of job to jenkins_job

### PR DESCRIPTION
**Pull request by chenfli**
The per job metrics are not working, I suspect that it is because of the job criteria see https://github.com/jenkinsci/prometheus-plugin/issues/45

### CODE REVIEW

**Comment by sacrebleu** [comment]
Rather than making this a breaking change, would it not make sense to implement this as a configurable field with a default being the old value?  That might make it more likely to be merged, which would be awesome because we've just run into this issue ourselves.

**Comment by lsjostro** [comment]
@sacrebleu yeah, that sounds much better.

**Comment by chenfli** [comment]
@sacrebleu / @lsjostro Changed and added a configurable attribute jobAttributeName. please approve.

**Comment by lsjostro** [comment]
looks good! thanks! let's roll a 2.0 release for this as it might be a breaking change for people.

**Pull request merged**
