### PR TITLE
Adding uptime monitor for Jenkins instance

### LINKED ISSUE #28: Feature request: Add metrics for UP and UPTIME
It would be nice to have these metrics exposed as well, it could be as:

- jenkins_up
- jenkins_uptime

Cheers!

### PR DESCRIPTION
**Pull request by jmcshane**
Resolves #28

### CODE REVIEW

**Comment by lsjostro** [comment]
https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fprometheus-plugin/detail/PR-50/1/pipeline#step-33-log-201

**Comment by jmcshane** [comment]
Sorry, I was doing some debugging and forgot to clean it up at the end. Cleaning up the PR now.

**Comment by markyjackson-taulia** [comment]
@jmcshane were you able to revisit this?

**Comment by jmcshane** [comment]
@markyjackson-taulia got around to it, should pass now

**Pull request merged**
