### PR TITLE
Add executor load statistics collector

### PR DESCRIPTION
**Pull request by msabastian**
### Changes proposed

- Add Collector for Executor Load Statistics
  (Data used in `http://<jenkins_url>/label/<label>/load-statistics`)

### Checklist

- [ ] Includes tests covering the new functionality?
  No collector class has corresponding tests.
- [X] Ready for review
- [x] Follows CONTRIBUTING rules

### Notify

@markyjackson-taulia

### CODE REVIEW

**Review by markyjackson-taulia — CHANGES_REQUESTED** [review]
Can you add a test?

**Comment by msabastian** [comment]
@markyjackson-taulia Could you provide examples for Collector tests? I couldn't find any references 🙏

**Comment by markyjackson-taulia** [comment]
@msabastian i will first thing in the morning if that is okay

**Review by markyjackson-taulia — APPROVED** [review]
I will give the examples for tests later tonight hopefully.

**Comment by msabastian** [comment]
Hi @markyjackson-taulia Don't mean to be naggy, but just a gentle reminder 😅 I'm trying to get this into our production env. Appreciate the help! :)

**Comment by markyjackson-taulia** [comment]
@msabastian  Unfortunately I am out sick and will not have a chance to write the test you need this week.
If you want to forge ahead and write the test, I will review it and release but I cannot release without a test.
Also, in terms of your production env needs, I sincerely apologize, but you are more than welcome to build your own .hpi for your production needs.

**Comment by markyjackson-taulia** [comment]
I still don't see the test.

**Comment by msabastian** [comment]
@markyjackson-taulia I was hoping to get a reference, cause none of the collectors have test right now 😅 also I pinged as you as a reminder 😛

**Comment by markyjackson-taulia** [comment]
Hello @msabastian 
I wanted to ping on a few things.
* I don't write tests for others feature request, I simply do not have the time for that.
* This branch has conflicts.

I will leave this PR open for a week to see if the test is added and if not, I will close.

**Comment by msabastian** [comment]
Hey @markyjackson-taulia, I just resolved the merge conflicts.

Also, I was not looking for somebody else to write tests for the class that I've added, but rather pointed out that **NO** collector in this project is tested. Hence, I have no reference on how to implement tests for the collector I've added (`ExecutorCollector`) and was looking for your help ☝🏾 and you replied

> I will give the examples for tests later tonight hopefully.

The issue I'm facing: I did not find any way to mock `hudson.model.Label.loadStatistics` as it is a `public final transient` field with the tooling you chose for your tests (in comparison, we heavily use Spock for our tests within my company).

This is how far I got:

```java
package org.jenkinsci.plugins.prometheus;

import hudson.model.Label;
import hudson.model.LoadStatistics;
import io.prometheus.client.Collector;
import jenkins.model.Jenkins;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.powermock.api.mockito.PowerMockito;
import org.powermock.core.classloader.annotations.PowerMockIgnore;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;
import static org.assertj.core.api.Assertions.assertThat;

import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

@RunWith(PowerMockRunner.class)
@PrepareForTest({Jenkins.class})
// PowerMockIgnore needed for: https://github.com/powermock/powermock/issues/864
@PowerMockIgnore({"com.sun.org.apache.xerces.*", "javax.xml.*", "org.xml.*", "org.w3c.*", "com.sun.org.apache.xalan.*"})
public class ExecutorCollectorTest {

    @Mock
    private Jenkins jenkins;

    @Mock
    private Label label1;

    @Mock
    private LoadStatistics loadStatistics1;

    @Mock
    private LoadStatistics.LoadStatisticsSnapshot loadStatisticsSnapshot1;

    @Mock
    private Set<Label> labels = new HashSet<Label>(){{
        add(label1);
    }};

    @Before
    public void setUp() {
        PowerMockito.mockStatic(Jenkins.class);
        PowerMockito.when(Jenkins.get()).thenReturn(jenkins);
        PowerMockito.when(jenkins.getLabels()).thenReturn(labels);

        PowerMockito.when(label1.getDisplayName()).thenReturn("Label 1");
        try {
            setFinalStatic(Label.class.getDeclaredField("loadStatistics"), loadStatistics1);
        }
        catch (SecurityException e) {Assert.fail("Exception: " + e);}
        catch (NoSuchFieldException e) {Assert.fail("Exception: " + e);}
        catch (Exception e) { Assert.fail("Exception: " + e); }

        PowerMockito.when(loadStatistics1.computeSnapshot()).thenReturn(loadStatisticsSnapshot1);
        PowerMockito.when(loadStatisticsSnapshot1.getAvailableExecutors()).thenReturn(1);
        PowerMockito.when(loadStatisticsSnapshot1.getBusyExecutors()).thenReturn(1);
        PowerMockito.when(loadStatisticsSnapshot1.getConnectingExecutors()).thenReturn(1);
        PowerMockito.when(loadStatisticsSnapshot1.getDefinedExecutors()).thenReturn(3);
        PowerMockito.when(loadStatisticsSnapshot1.getIdleExecutors()).thenReturn(2);
        PowerMockito.when(loadStatisticsSnapshot1.getOnlineExecutors()).thenReturn(1);
        PowerMockito.when(loadStatisticsSnapshot1.getQueueLength()).thenReturn(4);
    }

    @Test
    public void shouldCollectExecutorMetrics() {
        // given
        ExecutorCollector executorCollector = new ExecutorCollector();

        // when
        List<Collector.MetricFamilySamples> actual = executorCollector.collect();

        // then
        assertThat(actual.size()).isEqualTo(7);
    }

    static void setFinalStatic(Field field, Object newValue) throws Exception {
        // https://stackoverflow.com/a/23200308

        field.setAccessible(true);

        // remove final modifier from field
        Field modifiersField = Field.class.getDeclaredField("modifiers");
        modifiersField.setAccessible(true);
        modifiersField.setInt(field, field.getModifiers() & ~Modifier.FINAL);

        field.set(null, newValue);
    }
}

```

...but it throws `java.lang.AssertionError: Exception: java.lang.NullPointerException`.

**Pull request merged**
